services:
  mariadb:
    image: ${DOCKER_IMAGE_MARIADB}
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_DATABASE: ${PLAYSMS_DB_NAME}
      MARIADB_USER: ${PLAYSMS_DB_USER}
      MARIADB_PASSWORD: ${PLAYSMS_DB_PASS}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - playsms-network
    restart: unless-stopped

  playsms:
    image: ${DOCKER_IMAGE_PLAYSMS}
    environment: &playsms_vars
      - PLAYSMS_VERSION=${PLAYSMS_VERSION}
      - PLAYSMS_DB_NAME=${PLAYSMS_DB_NAME}
      - PLAYSMS_DB_USER=${PLAYSMS_DB_USER}
      - PLAYSMS_DB_PASS=${PLAYSMS_DB_PASS}
      - PLAYSMS_DB_HOST=${PLAYSMS_DB_HOST}
      - PLAYSMS_DB_PORT=${PLAYSMS_DB_PORT}
      - PHP_FPM_PORT=${PHP_FPM_PORT}
    build:
      dockerfile: Dockerfile
      args: *playsms_vars
    volumes:
      - playsms_web:/var/www/html
    depends_on:
      - mariadb
    networks:
      - playsms-network

  nginx:
    image: ${DOCKER_IMAGE_NGINX}
    environment:
      - NGINX_HTTP_PORT=${NGINX_HTTP_PORT}
      - NGINX_HTTPS_PORT=${NGINX_HTTPS_PORT}
      - PHP_FPM_PORT=${PHP_FPM_PORT}
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/ssl:/etc/nginx/ssl
      - playsms_web:/var/www/html
    depends_on:
      - playsms
    networks:
      - playsms-network
    ports:
      - "${NGINX_HTTP_PORT}:${NGINX_HTTP_PORT}"
      - "${NGINX_HTTPS_PORT}:${NGINX_HTTPS_PORT}"
    restart: unless-stopped

networks:
  playsms-network:
    driver: bridge

volumes:
  playsms_web:
  mariadb_data:
