services:
  mariadb:
    image: ${DOCKER_IMAGE_MARIADB}
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_DATABASE: ${PLAYSMS_DB_NAME}
      MARIADB_USER: ${PLAYSMS_DB_USER}
      MARIADB_PASSWORD: ${PLAYSMS_DB_PASS}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - playsms-network
    restart: unless-stopped

  nginx:
    image: ${DOCKER_IMAGE_NGINX}
    environment:
      - WEBSERVER_SERVER_NAME=${WEBSERVER_SERVER_NAME}
      - WEBSERVER_HTTP_PORT=${WEBSERVER_HTTP_PORT}
      - WEBSERVER_HTTPS_PORT=${WEBSERVER_HTTPS_PORT}
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/ssl:/etc/nginx/ssl
      - playsms_web:/var/www/html
    depends_on:
      - mariadb
    networks:
      - playsms-network
    ports:
      - "${WEBSERVER_HTTP_PORT}:80"
      - "${WEBSERVER_HTTPS_PORT}:443"
    restart: unless-stopped

  playsms:
    image: ${DOCKER_IMAGE_PLAYSMS}
    environment: &playsms_vars
      - PLAYSMS_VERSION=${PLAYSMS_VERSION}
      - PLAYSMS_DB_NAME=${PLAYSMS_DB_NAME}
      - PLAYSMS_DB_USER=${PLAYSMS_DB_USER}
      - PLAYSMS_DB_PASS=${PLAYSMS_DB_PASS}
      - PLAYSMS_DB_HOST=${PLAYSMS_DB_HOST}
      - PLAYSMS_DB_PORT=${PLAYSMS_DB_PORT}
    build:
      context: .
      dockerfile: Dockerfile
      args: *playsms_vars
    volumes:
      - playsms_log:/home/playsms/log
      - playsms_web:/home/playsms/web
    depends_on:
      - nginx
      - mariadb
    networks:
      - playsms-network
    restart: unless-stopped

networks:
  playsms-network:
    driver: bridge

volumes:
  playsms_web:
  playsms_log:
  mariadb_data:
