services:
  mariadb:
    image: ${DOCKER_IMAGE_MARIADB:-mariadb:lts}
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_DATABASE: ${PLAYSMS_DB_NAME:-mariadb}
      MARIADB_USER: ${PLAYSMS_DB_USER:-mariadb}
      MARIADB_PASSWORD: ${SERVICE_PASSWORD_PLAYSMSDBPASS}
      TZ: ${PLAYSMS_CONTAINER_TIMEZONE:-America/Chicago}
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 8s
      interval: 5s
      timeout: 5s
      retries: 3
    restart:
      unless-stopped

  playsms:
    image: ${DOCKER_IMAGE_PLAYSMS:-playsms/playsms:1.4.x}
    environment: &playsms_vars
      GID: ${GID:-1000}
      UID: ${UID:-1000}
      TZ: ${PLAYSMS_CONTAINER_TIMEZONE:-America/Chicago}
      PLAYSMS_VERSION: ${PLAYSMS_VERSION:-1.4.x}
      PLAYSMS_DB_NAME: ${PLAYSMS_DB_NAME:-mariadb}
      PLAYSMS_DB_USER: ${PLAYSMS_DB_USER:-mariadb}
      PLAYSMS_DB_PASS: ${SERVICE_PASSWORD_PLAYSMSDBPASS}
      PLAYSMS_DB_HOST: ${PLAYSMS_DB_HOST:-mariadb}
      PLAYSMS_DB_PORT: ${PLAYSMS_DB_PORT:-3306}
      WEB_ADMIN_PASSWORD: ${SERVICE_PASSWORD_WEBADMIN}
    build:
      context: .
      dockerfile: Dockerfile
      args: *playsms_vars
    volumes:
      - playsms-log:/home/playsms/log
      - playsms-web:/home/playsms/web
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      start_period: 8s
      interval: 10s
      timeout: 5s
      retries: 5
    restart:
      unless-stopped

  nginx:
    image: ${DOCKER_IMAGE_NGINX:-nginx:stable-alpine}
    environment:
      SERVICE_FQDN_NGINX_80: ${SERVICE_FQDN_NGINX_80}
      TZ: ${PLAYSMS_CONTAINER_TIMEZONE:-America/Chicago}
    volumes:
      - nginx-templates:/etc/nginx/templates
      - playsms-web:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy      
      playsms:
        condition: service_healthy      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1"]
      start_period: 5s
      interval: 10s
      timeout: 8s
      retries: 3
    restart:
      unless-stopped

volumes:
  mysql-data:
  playsms-log:
  playsms-web:
